### ISSUE TITLE
Arrows in gui don't work

### ISSUE THREAD

**Issue by Toxicstic** [OnlyNoobDied/GadgetsMenu#687] opened 2019-05-31 17:13 UTC
I customized the arrows in the gui of the hats, but now they lost their functionality. In the screenshot you can see that I only customized the message...
![2019-05-31_19 11 34](https://user-images.githubusercontent.com/51242540/58722614-20eba700-83d8-11e9-953a-effcaa73c766.png)

**Comment by Toxicstic** [comment] 2019-05-31 17:27
https://www.dropbox.com/s/98vvqj6x1iildqh/2019-05-31_19-24-29.mp4?dl=0
A short video where you can see the problem.

**Comment by OnlyNoobDied** [comment] 2019-05-31 23:07
I need your messages.yml file.

**Comment by OnlyNoobDied** [comment] 2019-06-03 08:58
Can I have your messages.yml file.

**Comment by OnlyNoobDied** [comment] 2019-06-08 03:28
@Toxicstic Any updates.

**Comment by Foxxite** [comment] 2019-06-08 10:08
Same issue when changing the coluor codes:


[messages.yml.txt](https://github.com/OnlyNoobDied/GadgetsMenu/files/3268409/messages.yml.txt)

**Comment by OnlyNoobDied** [comment] 2019-06-08 11:44
Give me the messages.yml that you have modified.
Like the Next Page Button `Volgende pagina`

**Comment by Foxxite** [comment] 2019-06-09 09:53
I already provided you with my messages.yml. In which I only changed the colour codes. And that breaks it as well. Meaning that this bug has something to do with incorrectly checking for item name., a.k.a. not using the messages.yml to check for the item name in this instance.

You should be more than capable to replicate this bug by setting up a quick test server, en changing the text of the next page arrow in the messages.yml yourself.

**Comment by OnlyNoobDied** [comment] 2019-06-09 09:55
No, that not the same as the picture you show to me.
```
  Next-Page:
    Name: '&fNext Page'
```

**Comment by Foxxite** [comment] 2019-06-09 09:56
`  Next-Page:
    Name: '&fVolgende Pagina'
`

Happy now?

**Comment by Foxxite** [comment] 2019-06-09 09:57
(Also that language is Dutch)

**Comment by OnlyNoobDied** [comment] 2019-06-09 09:58
I need the original messages.yml so I can test it.

**Comment by Foxxite** [comment] 2019-06-09 09:59
Can't you use this one, as the issue seems to appear when that string is changed?

https://github.com/OnlyNoobDied/GadgetsMenu/files/3268409/messages.yml.txt

**Comment by OnlyNoobDied** [comment] 2019-06-09 10:01
It works perfectly for me and I can't reproduce the problem that you said. So, I need the translated file and I can use it for testing.

**Comment by Foxxite** [comment] 2019-06-09 10:08
It might be an issue on 1.14.2 though. That's what I'm running and it doesn't work for me. And seeing the textures of the original poster, he is on 1.14 as well.

**Comment by OnlyNoobDied** [comment] 2019-06-09 10:09
What is the version of GadgetsMenu you're currently using?

**Comment by Foxxite** [comment] 2019-06-09 10:11
4.3.20

**Comment by OnlyNoobDied** [comment] 2019-06-09 10:23
I will fix this problem in the next update.

**Comment by Foxxite** [comment] 2019-06-09 10:32
👍

**Comment by OnlyNoobDied** [comment] 2019-06-22 04:31
Seems like this issue only happened when you use &f color code. I'm still finding a solution, sorry for the inconveniences.

**Comment by Foxxite** [comment] 2019-06-22 10:10
Can't you add a bit of custom NBT to the item and check for that? That should fix the name issues.

**Comment by OnlyNoobDied** [comment] 2019-06-22 10:16
I found a way to solve this problem, but it's not a long term solution.

**Comment by OnlyNoobDied** [comment] 2019-06-24 14:32
Thank you for reporting this issue, it will be fixed in the next update.

**Closed by OnlyNoobDied** 2019-06-24 14:32 UTC
Labels: Status: Resolved, Type: Bug
