### ISSUE TITLE
输入/ gadgetsmenu重新加载重载报错

### ISSUE THREAD

**Issue by 1425115471** [OnlyNoobDied/GadgetsMenu#721] opened 2019-10-15 07:05 UTC
版本：GadgetsMenu [1.8-1.14.4] [Premium] 4.5.5
服务器版本：spigot1.13.2
买家ID：mc_feifei

========报错内容
[15:01:40] [Server thread/INFO]: feifei issued server command: /gadgetsmenu main
[15:02:25] [Server thread/INFO]: feifei issued server command: /gadgetsmenu reload
[15:02:25] [Server thread/INFO]: [GadgetsMenu] Disabling GadgetsMenu v4.5.5
[15:02:27] [Server thread/WARN]: java.lang.NullPointerException
[15:02:27] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:57)
[15:02:27] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:42)
[15:02:27] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.reload(PluginUtils.java:37)
[15:02:27] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.commands.main.subcommands.CommandReload.lambda$0(CommandReload.java:50)
[15:02:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[15:02:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[15:02:27] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[15:02:27] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[15:02:27] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[15:02:27] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[15:02:27] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:02:34] [Server thread/INFO]: feifei issued server command: /gadgetsmenu main

**Comment by OnlyNoobDied** [comment] 2019-10-15 07:12
The reload command should never been used. I can't do any thing with it and I won't do anything If errors occur,

**Comment by OnlyNoobDied** [comment] 2019-10-15 07:12
Furthermore, I request for more info in your old issue but you didn't reply.

**Comment by OnlyNoobDied** [comment] 2019-10-15 07:13
Duplicate of #715

**Comment by 1425115471** [comment] 2019-10-15 07:14
不好意思当时没有在进行那个项目，我想测试新的披风，但是每次都要重新启动服务器-_-||

**Comment by OnlyNoobDied** [comment] 2019-10-15 07:16
Did you use the reload command when you update GadgetsMenu plugin but didn't restart the server?

**Comment by 1425115471** [comment] 2019-10-15 07:18
服务器完全启动后，GadgetsMenu插件功能使用正常，只有使用了reload命令才会出现报错，然后GadgetsMenu插件无法使用

**Comment by 1425115471** [comment] 2019-10-15 07:19
[15:09:06] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[15:09:06] [Server thread/INFO]: Done (46.176s)! For help, type "help"
[15:09:06] [Server thread/INFO]: [PlotSquared] -------- PlotSquared Update Check --------
[15:09:06] [Server thread/INFO]: [PlotSquared] You appear to be running the latest version of PlotSquared. Congratulations!
[15:09:06] [Server thread/INFO]: [PlotSquared] -------- PlotSquared Update Check --------
[15:09:06] [Server thread/INFO]: [CoreProtect] WorldEdit logging successfully initialized.
[15:09:07] [Server thread/INFO]: [QuickShop] Using economy system: CMIEconomy
[15:09:07] [Craft Scheduler Thread - 7/INFO]: [Vault] Checking for Updates ... 
[15:09:07] [Craft Scheduler Thread - 7/INFO]: [Vault] There was an issue attempting to check for the latest version.
[15:09:07] [Craft Scheduler Thread - 7/INFO]: [Vault] No new version available
[15:09:09] [Server thread/INFO]: Starting UUID caching[m
[15:09:09] [Craft Scheduler Thread - 7/INFO]: [0;30;1m[[0;33;22mP2[0;30;1m] [0;37;22mStarting player data caching for: world[m
[15:09:10] [Craft Scheduler Thread - 2/INFO]: [PlaceholderAPI] 162 placeholder expansions are available on the cloud.
[15:09:17] [Craft Scheduler Thread - 7/INFO]: [0;30;1m[[0;33;22mP2[0;30;1m] [0;37;22m[0;33;22mCached a total of: 11938 UUIDs[m
[15:13:53] [Server thread/INFO]: Skipping schedule G1 due to player amount[m
[15:15:18] [User Authenticator #1/INFO]: UUID of player feifei is 1e80c9da-f42b-3fc6-816f-41797dd5e0e3
[15:15:19] [Server thread/INFO]: feifei[/110.17.68.157:48391] logged in with entity id 1547 at ([scb]42.00209057521694, 131.0, -136.1664498959569)
[15:15:30] [Server thread/INFO]: feifei issued server command: /gadgetsmenu main
[15:15:40] [Server thread/INFO]: feifei issued server command: /gadgetsmenu main
[15:16:05] [Server thread/INFO]: feifei issued server command: /?
[15:16:07] [Server thread/INFO]: feifei issued server command: /gadgetsmenu main
[15:16:35] [Server thread/INFO]: feifei issued server command: /?
[15:16:37] [Server thread/INFO]: [0;33;22m将 [0;33;1m12 [0;33;22mx [0;33;1mTNT [0;33;22m([0;33;1m[0;33;22m) 给予玩家 [0;33;1mfeifei[m
[15:16:37] [Server thread/INFO]: [0;33;22m将 [0;33;1m12 [0;33;22mx [0;33;1mTNT [0;33;22m([0;33;1m[0;33;22m) 给予玩家 [0;33;1mfeifei[m
[15:16:37] [Server thread/INFO]: [0;33;22m将 [0;33;1m16 [0;33;22mx [0;33;1mGold Ore [0;33;22m([0;33;1m[0;33;22m) 给予玩家 [0;33;1mfeifei[m
[15:16:37] [Server thread/INFO]: Unknown command. Type "/help" for help.[m
[15:16:46] [Server thread/INFO]: feifei issued server command: /gadgetsmenu main
[15:18:28] [Server thread/INFO]: feifei issued server command: /spawn
[15:18:55] [Async Chat Thread - #0/INFO]: [0;36;22m[[0;31;1m大队长[0;36;22m][m[0;36;1m[[0;37;1mfeifei[0;36;1m][m[0;36;1m[[0;31;1m[21m妮可[0;36;1m][m[m[0;37;22m[21m : [m功能正常，我将输入:GadgetsMenu reload[m
[15:18:58] [Server thread/INFO]: feifei issued server command: /GadgetsMenu reload
[15:18:58] [Server thread/INFO]: [GadgetsMenu] Disabling GadgetsMenu v4.5.5
[15:19:00] [Server thread/WARN]: java.lang.NullPointerException
[15:19:00] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:57)
[15:19:00] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.load(PluginUtils.java:42)
[15:19:00] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.utils.PluginUtils.reload(PluginUtils.java:37)
[15:19:00] [Server thread/WARN]: 	at com.yapzhenyie.GadgetsMenu.commands.main.subcommands.CommandReload.lambda$0(CommandReload.java:50)
[15:19:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[15:19:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[15:19:00] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[15:19:00] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[15:19:00] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[15:19:00] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[15:19:00] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by OnlyNoobDied** [comment] 2019-11-10 07:36
Please reply the message otherwise I will close this issue.

**Closed** 2020-03-22 13:13 UTC
Labels: Resolution: Cannot Reproduce, Status: Won't fix
