### ISSUE TITLE
Purchase Click Error

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#57] opened 2016-12-21 03:45 UTC
This error shows up when someone attemts to purchase a cosmetic with mystery dust, and they don't receive their items they attempted to purchase.

[21:41:45] [Server thread/ERROR]: Could not pass event InventoryClickEvent to GadgetsMenu v3.6.0
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-916.1]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-916.1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-916.1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-916.1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1909) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-916.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.1]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at com.OnlyNoobDied.GadgetsMenu.cosmetics.purchasemenu.PurchaseManager.InvClickPurchaseMenu(PurchaseManager.java:92) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1119.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-916.1]
	... 16 more

**Comment by OnlyNoobDied** [comment] 2016-12-21 06:31
Duplicate of #50

**Closed by OnlyNoobDied** 2016-12-21 06:31 UTC
Labels: Duplicated, Resolved
