### ISSUE TITLE
How do I create a Custom Mystery Box?

### ISSUE THREAD

**Issue by 7UNL1GHT** [OnlyNoobDied/GadgetsMenu#592] opened 2018-09-08 09:53 UTC
Hey, I was wondering how you could create custom mysteryboxes with specific loot dropped from them and probably it's custom opening animation? And what's all the buzz with mysteryboxes folder, is it for creating boxes and if it is could you give me the code for it?

**Comment by Matocolotoe** [comment] 2019-02-18 23:16
I don't think you will be given the source code.
About custom mystery boxes, I think it's already implemented in premium version, see #607 and #524.

**Comment by OnlyNoobDied** [comment] 2019-10-03 13:16
You can't create custom Mystery Box yet.

Duplicate of #607

**Closed by OnlyNoobDied** 2019-10-03 13:16 UTC
