### ISSUE TITLE
1.16.1 ERROR InventoryClickEvent

### ISSUE THREAD

**Issue by donvdp** [OnlyNoobDied/GadgetsMenu#800] opened 2020-08-28 08:40 UTC
Our console is outputting allot of errors as described below. These errors occurse when a player clicks inside the gadgetmenu.

pastebin is down, so ive simple copy pasted it here below.

```
[08:49:39] [Server thread/ERROR]: Could not pass event InventoryClickEvent to GadgetsMenu v4.5.27
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 36
	at java.util.Arrays$ArrayList.get(Arrays.java:4351) ~[?:?]
	at net.minecraft.server.v1_16_R1.NonNullList.get(SourceFile:46) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.PlayerInventory.getItem(PlayerInventory.java:541) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[patched_1.16.1.jar:git-Paper-136]
	at com.yapzhenyie.GadgetsMenu.listeners.cosmetics.SelectItemListener.onPlayerClickItem(SelectItemListener.java:23) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor500.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-136]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2423) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-136]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Running:
 - Paper-136
 - GadgetsMenu v4.5.27

**Comment by OnlyNoobDied** [comment] 2020-08-28 09:33
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment] 2020-08-30 14:10
Duplicate of #798

**Closed** 2020-08-30 14:11 UTC
Labels: Resolution: Duplicated, Type: Bug
