### ISSUE TITLE
[Suggestion] A treasure Chest addon ;)

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#409] opened 2017-11-13 21:12 UTC
Hi, are you able to add a treasure chest thing?

Of course plugin will offer few animations.
Players can open from 1 to 8 treasure chest base on his permissions.

It could be nice ;)

Thank you

**Comment by OnlyNoobDied** [comment] 2017-11-13 21:18
What's the different between mystery boxes and treasure chest?

**Comment by maxlehot1234** [comment] 2017-11-13 21:20
Good question :P Or add ANOTHER way for players to open a mysterybox... Maybe by right-clicking an NPC.

Because having 9999 mystery vault was weird and take a lot of place...

Or allow players to open their mysterybox from anywhere could be much better too ;)

**Comment by OnlyNoobDied** [comment] 2017-11-13 21:23
oh, i gonna add some new animations. One of the animation is "none".

**Comment by maxlehot1234** [comment] 2017-11-13 21:58
#336

**Comment by OnlyNoobDied** [comment] 2017-11-14 08:09
What do you think if i add an option to disable animation for mystery box?

**Comment by maxlehot1234** [comment] 2017-11-14 08:18
It can be good but the big problem is that I need to create a lot of mystery vaults so each player can open their mysterybox :(

An NPC could be the best thing OR allow players to open thei mysterybox from anywhere.

They can do/box to open the mysterybox inventory and when they click on a box and they confirm that they want to open it, they will see particles, sounds and hologram 2 blocks in front of them that display the cosmetic they won.

It would be amazing if you can and I know you can do this :P

**Comment by TheIntelloBox** [comment] 2017-11-18 10:34
Could you add it so ? :D

**Comment by OnlyNoobDied** [comment] 2018-02-20 09:44
Duplicate of #314 
Duplicate of #498

**Closed** 2018-02-21 09:43 UTC
Labels: Duplicated, Suggestion
