### ISSUE TITLE
Remove all the cosmetics doesn't remove the hat of the Scarecrow gadget.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#430] opened 2017-12-10 15:20 UTC
Remove all the cosmetics doesn't remove the hat of the Scarecrow gadget.

**Comment by OnlyNoobDied** [comment] 2017-12-11 03:29
Duplicate of #428

**Closed by OnlyNoobDied** 2017-12-11 03:29 UTC
