### ISSUE TITLE
Error with PWP.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#429] opened 2017-12-10 15:09 UTC
[15:19:06] [Server thread/ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Could not pass event InventoryClickEvent to GadgetsMenu v4.1.0
org.bukkit.event.EventException: null
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[PerWorldPlugins.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_72]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_72]
	at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetScarecrow.clearAll(GadgetScarecrow.java:167) ~[GadgetsMenu%20(10).jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetScarecrow.onClear(GadgetScarecrow.java:149) ~[GadgetsMenu%20(10).jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.GadgetManager.unequipGadget(GadgetManager.java:83) ~[GadgetsMenu%20(10).jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.GadgetManager.checkRequirement(GadgetManager.java:107) ~[GadgetsMenu%20(10).jar:?]
	at com.yapzhenyie.GadgetsMenu.menu.menus.GadgetTypesMenu.onInvClickGadgets(GadgetTypesMenu.java:256) ~[GadgetsMenu%20(10).jar:?]
	at sun.reflect.GeneratedMethodAccessor1018.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[PerWorldPlugins.jar:?]
	... 16 more

**Comment by OnlyNoobDied** [comment] 2017-12-11 03:28
Duplicate of #428

**Closed** 2017-12-11 03:28 UTC
Labels: Duplicated
