### ISSUE TITLE
Shears of the Gadget "Explosive sheep" are usable

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#735] opened 2019-11-11 16:19 UTC
**Describe the bug**
The shears of the Gadget "Explosive sheep" are usable. In survival mode, we can cut grass and reduce the durability of the item. It's a duplication bug.

**To Reproduce**
1. Equip explosive sheep gadgets (shears)
2. Go to survival gamemode
3. Cut a block of grass, it should drop

**Expected behavior**
Action should be cancelled and we shouldn't be able to cut and get grass with them.

**Further Information (please complete the following information):**
- [13:04:57 INFO]: [GadgetsMenu] GadgetsMenu [Premium] 4.5.6 is loading...
- [13:04:57 INFO]: [GadgetsMenu] [server: git-Paper-650 (MC: 1.13.2)]

**Screenshots**
None

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?
None

**Comment by Aurelien30000** [comment] 2019-11-30 09:34
20 days on no answer :x
Sorry for disturbing but it's quite long, and I need a fix or at least a confirmation that you are aware of them, for my three issues. 

Thanks again :)

**Comment by OnlyNoobDied** [comment] 2019-11-30 14:39
I didn't reply this issue because I can't reproduce the same issue you have. This problem might by plugin conflicts.

**Comment by Aurelien30000** [comment] 2019-11-30 16:08
Quite strange, look at this video, with just 4 plugins that souldn't interact with Gmenu https://youtu.be/8g0PRUjF1GY ^^

**Comment by OnlyNoobDied** [comment] 2020-03-21 13:11
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment] 2020-03-22 08:01
This issue has been fixed. Please check for the new update.

**Closed by OnlyNoobDied** 2020-03-22 08:01 UTC
Labels: Type: Bug
