### ISSUE TITLE
[Suggestion] Opening box NEW SYSTEM

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#422] opened 2017-12-04 21:21 UTC
Hi, are you able to create something like this for box:
![afbdd5054fff9c083c46d1df3e132c07f176de1b](https://user-images.githubusercontent.com/5159244/33576748-e99e91c4-d90e-11e7-9658-fa00cdf501bc.gif)

Players CAN USE: ./mysterybox open OR any other command and a Gui will appear with all their mysterybox.
When players choose a box and accept to open it, he will see a GUI animation like the .gif above.

This could be MUCH BETTER than mysteryvaults.... Imagine with 50 players that want to oipen their mysterybox... They need to wait to get a "free" mystery vault...... This is something you need to change in your plugin.

Thank you so much and hope you will add this into your plugins or create an add-on for this ;)

**Comment by OnlyNoobDied** [comment] 2017-12-10 14:27
What do you think about the new animation "None"? It only takes 2 seconds to open a mystery box.

**Comment by maxlehot1234** [comment] 2017-12-16 17:09
@OnlyNoobDied It was great, but again, not the best thing ;)

Something to prevent the server owner to create mystery vault and allow the players to open their mystery box from ANYWHERE on the server or on an NPC could be the BIGGEST thing you can do and I am 100% sure that you can create this ;)

But it was better with "none", but not the best 


Thanks for your time

**Comment by TheIntelloBox** [comment] 2017-12-17 11:38
Yes add a Citizens compatibility please. :)

**Comment by OnlyNoobDied** [comment] 2017-12-17 14:30
@maxlehot1234  Why don't you create Mystery Vault?

**Comment by OnlyNoobDied** [comment] 2018-02-21 13:17
Duplicate of #498

**Closed** 2018-02-25 14:02 UTC
Labels: Duplicated
