### ISSUE TITLE
Found more bugs:

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#274] opened 2017-08-30 14:21 UTC
When i equip the mermaid suit and try to equip the spooderman suit you get this error:

[16:19:23 WARN]: java.lang.NullPointerException
[16:19:23 WARN]:        at com.yapzhenyie.GadgetsMenu.utils.cosmetics.morphs.LibDisguise.getDisguise(LibDisguise.java:19)
[16:19:23 WARN]:        at com.yapzhenyie.GadgetsMenu.cosmetics.suits.types.SuitMermaid.onClear(SuitMermaid.java:44)
[16:19:23 WARN]:        at com.yapzhenyie.GadgetsMenu.cosmetics.suits.SuitManager.unequipBoots(SuitManager.java:236)
[16:19:23 WARN]:        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.unequipSuitEquipment(PlayerManager.java:507)
[16:19:23 WARN]:        at com.yapzhenyie.GadgetsMenu.cosmetics.suits.SuitManager.equipBoots(SuitManager.java:91)
[16:19:23 WARN]:        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipSuitEquipment(PlayerManager.java:485)
[16:19:23 WARN]:        at com.yapzhenyie.GadgetsMenu.menu.menus.SuitEquipmentMenu.onInvClickSuitEquipment(SuitEquipmentMenu.java:321)
[16:19:23 WARN]:        at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source)
[16:19:23 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:19:23 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[16:19:23 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[16:19:23 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:19:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[16:19:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[16:19:23 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1878)
[16:19:23 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[16:19:23 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[16:19:23 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[16:19:23 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:19:23 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:19:23 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[16:19:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[16:19:23 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[16:19:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[16:19:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[16:19:23 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by OnlyNoobDied** [comment] 2017-08-30 15:12
Duplicate of #276

**Closed** 2017-08-31 07:55 UTC
Labels: Bug, Duplicated, Resolved
