### ISSUE TITLE
Reset Cosmetics glass moveable

### ISSUE THREAD

**Issue by HellaMixel** [OnlyNoobDied/GadgetsMenu#261] opened 2017-08-29 23:29 UTC
I can move the reset cosmetics glass from the gmenu around and place it in my inventory as an item and place it

**Comment by maxlehot1234** [comment] 2017-08-29 23:32
How you do this? Video, more explications? etc?

I try and can't reproduce this

**Comment by HellaMixel** [comment] 2017-08-29 23:49
https://vid.me/t6By0

**Comment by OnlyNoobDied** [comment] 2017-08-30 00:45
Did you get any errors in the console, send it to me.

**Comment by HellaMixel** [comment] 2017-08-30 00:57
Seems to be working now

**Comment by HellaMixel** [comment] 2017-08-30 01:12
Actually so when the config has an error and it gives a internal error but still allows the menu to open the class isn't movable but if the config doesn't have an error the class is movable. This is what I get when I click the glass.

29.08 20:10:32 [Server] ERROR Could not pass event InventoryClickEvent to GadgetsMenu v4.0.0
29.08 20:10:32 [Server] INFO org.bukkit.event.EventException
29.08 20:10:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
29.08 20:10:32 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
29.08 20:10:32 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 20:10:32 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
29.08 20:10:32 [Server] INFO Caused by: java.lang.NullPointerException
29.08 20:10:32 [Server] INFO at com.yapzhenyie.GadgetsMenu.player.GPlayer.getPlayerManager(GPlayer.java:25) ~[?:?]
29.08 20:10:32 [Server] INFO at com.yapzhenyie.GadgetsMenu.GadgetsMenu.getPlayerManager(GadgetsMenu.java:668) ~[?:?]
29.08 20:10:32 [Server] INFO at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.GadgetManager.unequipGadget(GadgetManager.java:40) ~[?:?]
29.08 20:10:32 [Server] INFO at com.yapzhenyie.GadgetsMenu.player.PlayerManager.unequipGadget(PlayerManager.java:517) ~[?:?]
29.08 20:10:32 [Server] INFO at com.yapzhenyie.GadgetsMenu.player.PlayerManager.unequipActiveCosmetics(PlayerManager.java:427) ~[?:?]
29.08 20:10:32 [Server] INFO at com.yapzhenyie.GadgetsMenu.menu.menus.MainMenu.onInvClickMainMenu(MainMenu.java:154) ~[?:?]
29.08 20:10:32 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
29.08 20:10:32 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
29.08 20:10:32 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
29.08 20:10:32 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
29.08 20:10:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom.jar:git-Spigot-db6de12-18fbb24]

**Comment by OnlyNoobDied** [comment] 2017-08-30 09:08
This issue would be fixed in the next update.

**Closed** 2017-08-30 09:08 UTC
Labels: Bug, Resolved
