### ISSUE TITLE
[Suggestion] Static NPC for discoball gadget

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#172] opened 2017-05-20 16:07 UTC
Hi is it possible to create something so I need to create a NPC and this NPC will ALWAYS have the discoball gadget.

So players can come near to him for the music ;)

It could be really nice I think.

Thank you

**Comment by OnlyNoobDied** [comment] 2018-02-21 13:21
Duplicate of #334

**Closed by OnlyNoobDied** 2018-02-21 13:21 UTC
Labels: Suggestion
