### ISSUE TITLE
These are not working:

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#272] opened 2017-08-30 11:04 UTC
- Teleport stick
ERROR: Could not pass event PlayerInteractEvent to GadgetsMenu v4.0.1
(Does not teleport)

- Paint trail
WARN: [GadgetsMenu] Task #897 for GadgetsMenu v4.0.1 generated an exception
(Says it is already active when held, SPAMS this warning in console)

- Fire trail
(Gives speed, but does not put fire)

- Radio gadget
(Only shows default songs, none of the ones i've added)

- Paintball gun
WARN:
[GadgetsMenu] Task #1409 for GadgetsMenu v4.0.1 generated an exception
[GadgetsMenu] Task #1411 for GadgetsMenu v4.0.1 generated an exception
[GadgetsMenu] Task #1412 for GadgetsMenu v4.0.1 generated an exception
[GadgetsMenu] Task #1413 for GadgetsMenu v4.0.1 generated an exception
[GadgetsMenu] Task #1414 for GadgetsMenu v4.0.1 generated an exception
[GadgetsMenu] Task #1415 for GadgetsMenu v4.0.1 generated an exception
[GadgetsMenu] Task #1428 for GadgetsMenu v4.0.1 generated an exception
(Does not put paint)

- Pyromanic
(Does not put fire)

- Reset cosmetics button
ERROR:
Could not pass event InventoryClickEvent to GadgetsMenu v4.0.1

***I'll let you know if i find anything else :)***

**Comment by OnlyNoobDied** [comment] 2017-08-30 13:53
what's your server version.

**Comment by OnlyNoobDied** [comment] 2017-08-30 14:07
1) Teleport Stick Gadget, Paint Trail Gadget, Fire Trail Gadget, Let It Snow Gadget, Cowboy Gadget, Paintball Gun Gadget doesn't working due worldguard region checking. 
This issue would be fixed in the next update.

**Comment by xXIOSCARIXx** [comment] 2017-08-30 14:12
This plugin has a lot of unnecessary feautures that i dont want to use..
can you clean the .jar and remove

- mysterydust
- mysteryboxes
- lore messages
- worldguard intergration
- etc etc etc..

i want a simple and clean plugin <3

**Comment by OnlyNoobDied** [comment] 2017-08-30 14:45
For Fire trail gadget and Pyromanic gadget issue are depending on WorldGuard plugin. It controls fire-spawn

**Comment by OnlyNoobDied** [comment] 2017-08-30 14:46
Can you send me this error log. 

> Reset cosmetics button
ERROR:
Could not pass event InventoryClickEvent to GadgetsMenu v4.0.1

**Comment by xXIOSCARIXx** [comment] 2017-08-30 14:50
[16:44:46 ERROR]: Could not pass event InventoryClickEvent to GadgetsMenu v4.0.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1878) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
        at com.yapzhenyie.GadgetsMenu.utils.cosmetics.morphs.LibDisguise.getDisguise(LibDisguise.java:19) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.suits.types.SuitMermaid.onClear(SuitMermaid.java:44) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.suits.SuitManager.unequipHelmet(SuitManager.java:134) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.cosmetics.suits.SuitManager.unequipSuit(SuitManager.java:104) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.unequipSuit(PlayerManager.java:466) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.player.PlayerManager.unequipActiveCosmetics(PlayerManager.java:426) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.menu.menus.MainMenu.onInvClickMainMenu(MainMenu.java:154) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.1.jar:git-Spigot-65e8124-79e55b6]
        ... 15 more

**Comment by xXIOSCARIXx** [comment] 2017-08-30 15:04
By the way! it is: "This issue will be fixed in the next update."
saying "This issue would be fixed in the next update." can be confusing :)

**Comment by OnlyNoobDied** [comment] 2017-08-30 15:14
Thanks for correcting me. My english is not well. 
Duplicate of #276

**Closed** 2017-08-31 07:55 UTC
Labels: Bug, Duplicated, Resolved
