### ISSUE TITLE
Morph slimeball is not adding to inventory

### ISSUE THREAD

**Issue by UnioDex** [OnlyNoobDied/GadgetsMenu#531] opened 2018-04-17 10:33 UTC
When i activate a morph slimeball is not adding to inventory and i can't use the ability.

TacoSpigot: 1.8.8
GadgetsMenu: 4.1.17

**Comment by OnlyNoobDied** [comment] 2018-04-17 12:05
Duplicate of #532

**Closed by OnlyNoobDied** 2018-04-17 12:05 UTC

**Comment by OnlyNoobDied** [comment] 2018-04-17 13:57
Yup. You can download for free.

>
