### ISSUE TITLE
[BUG 4.0.10] Players can't see their disguise

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#360] opened 2017-09-19 19:51 UTC
If I choose a disguise, I can't see it.

I try to enable sef view, but change nothing.

Other players see my dsguise, but not me :(

Could you fix this please?

**Comment by OnlyNoobDied** [comment] 2017-09-19 21:03
Are you using iDisguise plugin?

**Comment by maxlehot1234** [comment] 2017-09-19 21:03
No Libs'Disquise

**Comment by OnlyNoobDied** [comment] 2017-09-19 21:07
Oh, set "Enabled-Self-Morph-View" to true in config

**Comment by maxlehot1234** [comment] 2017-09-19 21:10
I doesn't have this into config.yml.

**Comment by OnlyNoobDied** [comment] 2017-09-19 21:13
in "settings" section.

**Comment by maxlehot1234** [comment] 2017-09-19 21:14
NOPE, I have this:
Settings:
  Default-Pet-Name: '&bAnimal de {PLAYER}'
  Starting-Mystery-Dust: 0
  Max-Pet-Name-Characters: 20
  Gadget-Slot: 5

Like you config.yml example on the wiki: https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Config

**Comment by OnlyNoobDied** [comment] 2017-09-19 21:16
Alright, please give me some time. I will release a fix version when i back
from school. It's now 5:16am

**Comment by maxlehot1234** [comment] 2017-09-19 21:17
Ohh, it is 17h16 (September 19) here :P

**Comment by xion87** [comment] 2017-09-19 21:31
yeah is the same issue that i have

**Comment by OnlyNoobDied** [comment] 2017-09-19 21:34
i knew the problem. If you want a fix it immediately. Try to remove
"Settings" section and reload the plugin.Then, you will see
"Enabled-Self-Morph-View".

**Comment by xion87** [comment] 2017-09-19 21:37
i will wait the new release don't worry ^^

**Comment by OnlyNoobDied** [comment] 2017-09-19 21:38
Okay, thanks.

**Comment by OnlyNoobDied** [comment] 2017-09-20 08:24
Duplicate of #358

**Closed by OnlyNoobDied** 2017-09-20 08:24 UTC
Labels: Bug, Duplicated, Resolved

**Comment by OnlyNoobDied** [comment] 2017-09-20 09:59
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=188464
