### ISSUE TITLE
Iron golem ability bugs blocks

### ISSUE THREAD

**Issue by Segysmundo** [OnlyNoobDied/GadgetsMenu#699] opened 2019-07-01 16:01 UTC
**Describe the bug**
People use the iron golem's morph ability and now and then I find bugged blocks that have been raised up by the golem's ability and don't go back down, I have to break  and place them as they originally were.

**To Reproduce**
1. Equip iron golem morph
2. Use its ability
3. Sometimes raised blocks don't go back down

**Expected behavior**
Right now we have to check out the spawn on a daily basis to see if there are any blocks out of place due to the blocks getting bugged, the ability could be more reliable.

**Further Information (please complete the following information):**
 - Server Version: PaperSpigot 1.13.2
 - GadgetsMenu Version: 4.4.18

**Screenshots**
Before using the ability
![image](https://user-images.githubusercontent.com/19178945/60450383-0e100080-9c2a-11e9-92b6-e9f88f5fac1c.png)

After using the ability
![image](https://user-images.githubusercontent.com/19178945/60450397-15370e80-9c2a-11e9-9bd6-a6432c746b30.png)

**Additional Information**
It seems to mostly happen next to walls.

**Comment by OnlyNoobDied** [comment] 2019-07-05 04:31
Can you contact me on spigot for further information?

**Comment by OnlyNoobDied** [comment] 2019-07-07 14:07
@Segysmundo Can you contact me on spigot for further information?

**Comment by OnlyNoobDied** [comment] 2019-07-13 14:16
I found that this problem is very difficult to solve. It caused by the upside down stone stair.

**Comment by OnlyNoobDied** [comment] 2019-09-02 10:17
This issue will be fixed in the next update.

**Comment by amnrmain** [comment] 2019-09-22 11:43
Can you give an estimated date?

This can be used to duplicate objects and is a bit annoying.

Thank you

**Comment by OnlyNoobDied** [comment] 2019-09-23 02:44
Sorry, could you disable the ability till the update release? I'm working on it.
May I know your buyer details?

**Comment by OnlyNoobDied** [comment] 2019-09-26 08:06
This issue has been fixed. Please check for the new update.

**Closed by OnlyNoobDied** 2019-09-26 08:06 UTC
Labels: Status: Resolved, Type: Bug
