### ISSUE TITLE
Couldnt Load Plugin

### ISSUE THREAD

**Issue by LostUmbrella58** [OnlyNoobDied/GadgetsMenu#982] opened 2024-11-24 16:42 UTC
This happened to the latest GadgetsMenu plugin.

This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) (The latest version)

and below is error log:

[23:29:07 INFO]: [GadgetsMenu] Enabling GadgetsMenu v5.19.0
[23:29:07 INFO]: [GadgetsMenu] ------------------------------------------------------
[23:29:07 INFO]: [GadgetsMenu]       GadgetsMenu [Premium] 5.19.0 is loading...
[23:29:07 INFO]: [GadgetsMenu]       [server: 1.21.1-132-b48403b (MC: 1.21.1)]
[23:29:07 INFO]: [GadgetsMenu]                  Running Java 21.0.3
[23:29:07 INFO]: [GadgetsMenu]                Plugin by Yap Zhen Yie.
[23:29:07 INFO]: [GadgetsMenu]            Date Modified: 24 November 2024
[23:29:07 INFO]: [GadgetsMenu]
[23:29:07 INFO]: [GadgetsMenu]              Initializing module v1_21_R1
[23:29:07 INFO]: [GadgetsMenu] ------------------------------------------------------
[23:29:07 ERROR]: Error occurred while enabling GadgetsMenu v5.19.0 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound org.bukkit.Sound.valueOf(java.lang.String)' must be Methodref constant
        at GadgetsMenu.jar/com.yapzhenyie.GadgetsMenu.utils.SoundEffect.<clinit>(SoundEffect.java:1547) ~[GadgetsMenu.jar:?]
        at GadgetsMenu.jar/com.yapzhenyie.GadgetsMenu.cosmetics.pets.types.EntityAllay.<init>(EntityAllay.java:13) ~[GadgetsMenu.jar:?]
        at GadgetsMenu.jar/com.yapzhenyie.GadgetsMenu.cosmetics.pets.TypeManager.initializePets(TypeManager.java:19) ~[GadgetsMenu.jar:?]
        at GadgetsMenu.jar/com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:316) ~[GadgetsMenu.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by rafi67000** [comment] 2024-11-24 21:42
happens on 1.12.2 too.

**Comment by Mitality** [comment] 2024-11-25 08:13
duplicate of [#981](https://github.com/yapzhenyie/GadgetsMenu/issues/981)

**Comment by yapzhenyie** [comment] 2024-11-25 14:49
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment] 2024-11-26 15:10
This issue has been fixed. Please check for the new update.

**Closed as completed by yapzhenyie** 2024-11-26 15:10 UTC
Labels: Type: Bug, Resolution: Duplicated
