### ISSUE TITLE
Tic Tac Toe still having some issues

### ISSUE THREAD

**Issue by topthat177** [OnlyNoobDied/GadgetsMenu#675] opened 2019-04-25 02:17 UTC
**Describe the bug**
Thanks for the fix. The issue with not being able to do it because you had a cosmetic equipped has been Resolved. Still receiving the unknown command messages etc. I attached a video to show you whats going on.

https://vimeo.com/332361399

**Further Information (please complete the following information):**
 - Server Version: 1.12.2
 - GadgetsMenu Version: 4.3.11
 - Console stack trace if have: N/A

**Comment by OnlyNoobDied** [comment] 2019-04-25 02:23
Just ignore that message.

>

**Comment by OnlyNoobDied** [comment] 2019-05-09 14:19
Do you still have the same issue? Actually I can't reproduce the problem you have.

**Comment by topthat177** [comment] 2019-05-10 05:08
Yes its still got some bugs for me. When ever someone issues the command /tictactoe accept [playername] by pressing the words in the chat. It will work but it will seed them an unknown command message for some reason. Also if Player 2 who received an invite to play from player 1 accepts then leaves mid game --> If Player 2 then invites Player 1 to a game. When Player 1 presses accept, it will say that he doesn't have a pending request from player 2.

This is really hard to explain. I tried to show in the video. Im now running the latest version .14 and its still having issues. Even if both players are OP'ed with all privileges. 

Im happy to arrange a time for you to come on my server and see for yourself if that helps.

**Comment by OnlyNoobDied** [comment] 2019-05-20 13:44
Thank you for reporting this issue, it will be fixed in the next update.

**Closed by OnlyNoobDied** 2019-05-20 13:44 UTC
Labels: Status: Resolved, Type: Bug
