### ISSUE TITLE
MysteryBoxes

### ISSUE THREAD

**Issue by ZeLFaDore** [OnlyNoobDied/GadgetsMenu#481] opened 2018-01-25 00:20 UTC
Hi there 

1- I noticed that when any player open a mysteryboxes and find any loot ( Common - Rare - Epic - Legendary ) it doesn't open it in the menu selector

2- How to give players random chest in a random time ?

3- Is there is any way to change the sound of opening mysteryboxes ?

4- I made a mysteryboxes new animation for example Test when any player tried to open any box with that animation it said ( You don't have the required permission gadgetsmenu.animations.normal

5- If a player has lag they can add multiple menu selector in their inventory
( https://imgur.com/SWKhXuK )

6- When a player send a gift to any player it shows the massage that they revised the gift but they can't open it 

7- I'm trying to translate your plugin from English to my language but I can't translate this I also searched all over the fills and I didn't find it 
( https://imgur.com/O2UoQbC )

If there is any way to fix them please reply me in the shortest time 
Thanks :)

**Comment by maxlehot1234** [comment] 2018-03-04 20:27
1- No idea :( Sorry
2- What do you mean exactly?
3- No :( A good thing to add in the plugin later if the dev want it
4- You can't create a new one, since how the plugin will know what is the effect of this animation?
5- Occured to me only, but they can't do anything with these things
6- They can't see them in their inventory gift section in mysteryvault gui i think
7- Check the: /plugins/GadgetsMenu/categories/mainmenu.yml

I am not the dev, just here to help you.

**Comment by OnlyNoobDied** [comment] 2018-03-05 11:20
Duplicate of #500

**Closed by OnlyNoobDied** 2018-03-05 11:20 UTC
