### ISSUE TITLE
Radio and discoball gadgets bugs [4.0.0]

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#256] opened 2017-08-29 23:00 UTC
Hi,

The radio and discoball gadgets stop working fro few milliseconds sometimes.

Also, there is no error in the console, no TPS issue like olders versions.

Any way to fix this?

Thank you

**Comment by OnlyNoobDied** [comment] 2017-08-30 09:20
What's server version?

**Comment by OnlyNoobDied** [comment] 2017-08-31 15:25
I tested it, it's working. Did you turn off Jukebox/Note blocks sound in your personal settings?

**Comment by OnlyNoobDied** [comment] 2017-09-19 09:26
Is this issue still occur?

**Comment by maxlehot1234** [comment] 2017-09-19 09:28
@OnlyNoobDied Yes it occured sometimes again.
It disappear in 4.0.1 and 4.0.2, but come back again in the other versions :(

**Comment by OnlyNoobDied** [comment] 2017-12-17 09:51
Is lag caused this issue?

**Comment by OnlyNoobDied** [comment] 2017-12-20 10:54
Close this issue due to outdated. You can still reply here if this issue still occur. However I think this issue caused by lagging

**Closed by OnlyNoobDied** 2017-12-20 10:54 UTC
Labels: Bug
